### PR TITLE
add helm chart for agent

### PR DESCRIPTION
**Pull request by jseguillon**
solve #18 

Signed-off-by: Joel Seguillon <joel.seguillon@gmail.com>

### CODE REVIEW

**Comment by aylei** [comment]
Great works, you made my day!

**Comment by jseguillon** [comment]
You're welcome. Thanks for your great work 👍

**Comment by jseguillon** [comment]
As a side note : this chat misses a Service Account and PodSecurePolicy don't you think ?

**Comment by aylei** [comment]
> As a side note : this chat misses a Service Account and PodSecurePolicy don't you think ?

I don’t have an idea actually. These seems nice to have as long as some proper defaults are provided.

**Pull request merged**
