### PR TITLE
agent pod pull secret

### PR DESCRIPTION
**Pull request by kchenzhi**
1. Add a param AgentImagePullPolicy(agent-pull-policy in command line) for agentless mode, default value: PullIfNotPresent.
2. Add a param AgentImagePullSecretName(agent-pull-secret-name in command line) for agentless mode, default empty.

This may useful when pulling agent image from private registry, 
such as: #109 , #89

### CODE REVIEW

**Comment by chinglinwen** [comment]
why still not merged after three month?

**Comment by chinglinwen** [comment]
I'd expect it skill pull image for debug-image ( not agent-image ) too.

**Comment by kchenzhi** [comment]
Maybe the owner needs to consider more situations before merge.

**Comment by chinglinwen** [comment]
It seems that this repo is a prototype, there is official kubectl debug. however I try to using your fork, and try to  find out how to skip pull image myself, got no luck.

from my test, agent-image must be pullable (here mine is harbor) for debug to work. which my requirement is debug offline(with pre loaded image).

> https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container
> Debugging with an ephemeral debug container
> FEATURE STATE: Kubernetes v1.18 [alpha]

**Review by aylei — APPROVED** [review]
LGTM

**Comment by aylei** [comment]
> It seems that this repo is a prototype, there is official kubectl debug. however I try to using your fork, and try to find out how to skip pull image myself, got no luck.

@chinglinwen  Yes this repository is a prototype and is not yet production-ready. About skipping pulling, I think it is not possible in `agentless` mode of current version, because the `imagePullPolicy` is unfortunately hard coded to `Always`. A workaround is to deploy a [debug-agent DaemonSet](https://github.com/aylei/kubectl-debug/blob/master/contrib/helm/kubectl-debug/templates/agent-ds.yaml) and run `kubectl-debug` with `--agentless=false` (or you can configure this in your preference file), thus you can specify the imagePullPolicy of debug-agent on your own.

**Comment by chinglinwen** [comment]
Thanks for your information @aylei , it's helpful to me !

**Comment by chinglinwen** [comment]
> @chinglinwen Yes this repository is a prototype and is not yet production-ready. About skipping pulling, I think it is not possible in agentless mode of current version, because the imagePullPolicy is unfortunately hard coded to Always. A workaround is to deploy a debug-agent DaemonSet and run kubectl-debug with --agentless=false (or you can configure this in your preference file), thus you can specify the imagePullPolicy of debug-agent on your own.

Hi @aylei, I'm ok with agent-image, I got issue that debug image need to pull, which cause issue for offline mode. 

```
# docker images|grep 1/netsh
127.0.0.1/netshoot                                                                 2020-9-16                83c35031e4c0        8 months ago        204MB

kubectl debug -n openstack netshoot-lpc5j --image 127.0.0.1/netshoot:2020-9-16 -a=false --pull-image=false

pulling image 127.0.0.1/netshoot:2020-9-16...
error execute remote, Internal error occurred: error attaching to container: Error response from daemon: Get http://127.0.0.1/v2/: dial tcp 127.0.0.1:80: connect: connection refused
error: Internal error occurred: error attaching to container: Error response from daemon: Get http://127.0.0.1/v2/: dial tcp 127.0.0.1:80: connect: connection refused
```
```
2020/09/23 06:17:07 receive debug request
2020/09/23 06:17:07 Accept new debug reqeust:
         target container: e67519f02c3f73db0b59a78b9acae742b5dc34223b883a97637724416b295862
         image: 127.0.0.1/netshoot:2020-9-16
         command: [bash]
E0923 06:17:07.264069     473 attach.go:52] error attaching to container: Error response from daemon: Get http://127.0.0.1/v2/: dial tcp 127.0.0.1:80: connect: connection refused

```

Do you know how to skip netshoot image pull ? @aylei

**Comment by chinglinwen** [comment]
For now, I can only think of a wary to run a registry in local, so make it pull success, that way it can works without touch real registry.

**Comment by shaneing** [comment]
Now, how to pull an image if not present?

**Comment by kchenzhi** [comment]
> Now, how to pull an image if not present?

Docker will pull the image if it is not present

**Comment by shaneing** [comment]
> > Now, how to pull an image if not present?
> 
> Docker will pull the image if it is not present

Why I can't:

```
❯ kubectl debug service-rev-proxy-f5f7489bf-t7hp9 --namespace dev -c istio-proxy
Agent Pod info: [Name:debug-agent-pod-cfd64f00-4465-11eb-acb9-3c7d0a05d6a3, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-cfd64f00-4465-11eb-acb9-3c7d0a05d6a3 to run...
Forwarding from 127.0.0.1:10027 -> 10027
Forwarding from [::1]:10027 -> 10027
Handling connection for 10027
                             Start deleting agent pod service-rev-proxy-f5f7489bf-t7hp9
error execute remote, Internal error occurred: error attaching to container: Error: No such image: docker.io/nicolaka/netshoot:latest
error: Internal error occurred: error attaching to container: Error: No such image: docker.io/nicolaka/netshoot:latest
```

Version:

```
❯ kubectl debug --version
debug version 0.2.0-rc
```

**Comment by Slach** [comment]
@shaneing cause https://hub.docker.com/nicolaka/netshoot really doesn't exist

**Comment by andrey-gava** [comment]
Same problem as @shaneing have. Pushed retaged image to my local repo. 
When do `docker pull nexus.dtech.com/nicolaka-netshoot:022021` its ok.
But 
`kubectl-debug --agentless=false --port-forward --image nexus.dtech.com/nicolaka-netshoot:022021 admin-59f5f56597-mdvn9 -c admin`
says:
```
Forwarding from 127.0.0.1:10027 -> 10027
Forwarding from [::1]:10027 -> 10027
Handling connection for 10027
                             error execute remote, Internal error occurred: error attaching to container: Error: No such image: nexus.datas-tech.com/nicolaka-netshoot:022021
error: Internal error occurred: error attaching to container: Error: No such image: nexus.dtech.com/nicolaka-netshoot:022021
```
```
kubectl debug --version
debug version 0.2.0-rc
```
@aylei Can it be fixed? Because many people in environment without access to Internet waiting for this future.

**Pull request merged**
